{
 "title": "Namespace dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Web page gen time sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (web_page_gen_time_sum{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Web page gen time count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (web_page_gen_time_count{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Web page gen time bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (web_page_gen_time_bucket{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Web pages served",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (web_pages_served{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Crawler page parse_time sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_page_parse_time_sum{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Crawler page parse time count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_page_parse_time_count{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Crawler page parse time bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_page_parse_time_bucket{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Crawler site connection time sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_site_connection_time_sum{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Crawler site connection time count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_site_connection_time_count{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Crawler site connection time bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_site_connection_time_bucket{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Crawler pages parsed (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_pages_parsed{kubernetes_namespace=~\"^$namespace$\"}[1m]))"
    }
   ]
  }
 ]
}