---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3
        name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password
